AdminUser.create!([
  {email: "admin@example.com", password: "password", password_confirmation: "password"}
])  
User.create!([
  {username: "Damon Hopkins", email: "damon@hopkins-family.org", password: "password", password_confirmation: "password"}
])
Photo.create!([
  {page_name: "cover", caption: "Jenny and baby Lizzy 1996", sequence: 1},
  {page_name: "FMN Products", caption: "Forget Me Not Products", sequence: 1},
  {page_name: "Soap", caption: "I Make Soap", sequence: 1},
  {page_name: "Lettermark", caption: "Lettermark Screenshot", sequence: 1},
  {page_name: "EDI Mapping", caption: "EDI Maping Pic", sequence: 1},
  {page_name: "Web Services", caption: "Features Screenshot", sequence: 1},
  {page_name: "Jesse Osborne", caption: "Jesse Osborne Dallas Tx", sequence: 1},
  {page_name: "Jesse Osborne", caption: "Jesse Osborne Dallas Tx", sequence: 2},
  {page_name: "Jesse Osborne", caption: "Jesse Osborne Dallas Tx", sequence: 3},
  {page_name: "Jesse Osborne", caption: "Jesse Osborne Dallas Tx", sequence: 4},
  {page_name: "Jesse Osborne", caption: "Jesse Osborne Dallas Tx", sequence: 5}
])
Style.create!([
  {stylename: "Default Reds", description: "DarkRed Coral and Tomato", primary_font: "Roboto", secondary_font: "Lobster Two", alt_font: "Times New Roman", primary_color: "#ff1616", secondary_color: "#ae0000", alt_color: "#ffd2c5"},
  {stylename: "Default Blues", description: "Basic Style Blue and Cyan", primary_font: "Lobster Two", secondary_font: "Lobster Two", alt_font: "Lobster Two", primary_color: "#65d8ff", secondary_color: "#0a03ad", alt_color: "#959cb7"},
  {stylename: "Default Greens", description: "Basic Greens", primary_font: "Lobster Two", secondary_font: "Lobster Two", alt_font: "Lobster Two", primary_color: "#c1ffc1", secondary_color: "#cacdca", alt_color: "#31ff37"}
])
Item.create!([
  {title: "Cover Page Project", heading: "Working with ActiveStorage", body: "Lots to do.. to get active storage to work with having things hosted in the cloud vs on the local file system.\r\nDuring deployment I learned all kinds of good things dealing with putting the configuration into environment variables. All new things but seem like valid concepts. Lots to manage in the ENV though.\r\nBack in the day you set your environment and you were done. Not so these days.\r\n<a href=\"/\" class=\"btn btn-sm btn-secondary\">Visit</a>", style_id: 1, user_id: 1, photo_id: 1},
  {title: "Forget Me Not Apothecary", heading: "Landing page", body: "Links to Social Media and Ecommerce Services\r\n<a href=\"https://fmn-apothecary.herokuapp.com\" class=\"btn btn-sm btn-outline-success bgdark\">Visit</a>", style_id: 2, user_id: 1, photo_id: 2},
  {title: "Soap", heading: "Hand Made Soap", body: "<h3>All the Finest Artisan Soap</h3>\r\n<p>All natural old fashioned soap with handmade labels. It's a hobby of mine. I haven't made soap in quite a few years.</p>", style_id: 3, user_id: 1, photo_id: 3},
  {title: "Lettermark Email System", heading: "Templates Before Templates were Cool", body: "<div style=\"background: rgb(0, 0, 0) transparent; background: rgba(32, 127, 32, 0.5);\">I returned a few years later I didn't just do the EDI Mapping projects there. I also worked on a large email branding service utilizing a microsoft outlook plug in to manipulate outgoing mail to ensure a consitiant look and feel went out with each email. They are still using the same system I worked on and practically rewrote from almost 10 years ago. Complete with the same home They appear to have stopped selling the Lettermark Encryption Plug-in for MS Outlook I presume due to the fact that it is akin to hacking your own email. We had to catch the message before it sent but after the security checks and Microsoft tries to make the message secure. We also developed our own suite of portable applications and a stand alone encryption product as well. You can see those things and poke around in the support wiki and see more about what I did there. Many people worked to build the lettermark system but the portable security suite were mainly developed by myself and one other developer. The entire suite of applications were registered and updated via an Active-X plugin we built our own license applications and used the webupdate system to validate ownership of the device buy generating a device specific license file to prevent piracy or the software. It was pretty fancy for it's day. The order of events were to log-in pick your device from those our plugin detected. At the time 512 MB USB devices were all the raee. We sold quite a few. You can see some of my Letermark work in the Logs</div>", style_id: 3, user_id: 1, photo_id: 4},
  {title: "EDI Mapping Project", heading: "X12 ASC Vans and ECommerce", body: "<div class=\"bgdark\" style=\"color: lightblue;\">The big project I worked on was an EDI Mapping Portal Service using VB then C++ and eventually C#. Clients would use our web-based service to do their X12 mapping translations for the transmission of electronic data between to different legacy systems in a scified protocol. We positioned outrselves into being a SaaS provider and you can still read the old press releases as well as look through the old documentation. The project started off as a VB5 app running on 2 large DEC Alpha servers with NT Server running IIS. We also managed the internal network of offices and all the internal and external support and service calls. We built ourselves an Astrix based PBX phone system and integrated that into our network as well. Occasionally we had local clients and serviced them with other developmental needs. A client needed to migrate from using Novell Netware 5 to NT Server Platform and I did that as well as a lot of work on their shared Microsoft Access database which managed the entire company I think. it was a database built like an desktop application. Thanks Form Wizard. . Besides that we did other fn projects like integrate a UMich Directory server for which I wrote the server side API service and another employee built the client plug in for our windows NT machines so we could have a centralized directory to authenticate to. This is common practice now and every one does it. But back then you authentecated to a domain and it was an entire diffrent beast. We wrote scripts and helpers wherever needed so it because our all-in-one authenticator. A year or so later Microsoft announced They too had a directory server. Netscape used it first commercially for their browser product but I came up witht he Authentication Server. Built it all from scratch in C and C++ and now you use OMNIAuth. and it's getting more and more common everyday on the internet. But back in 1999 or whatever ear that was.. I think we were the only ones doing it. I left the company for a few years to pursuse some colled classes and start a family.</div>", style_id: 2, user_id: 1, photo_id: 5},
  {title: "Web Services", heading: "Creating Websites for you", body: "Custom solutions for a personalized experience straight to your website. See what I can do for you\r\n<a href=\"/features\" class=\"btn btn-sm btn-outline-success\">More Info</a>", style_id: 2, user_id: 1, photo_id: 6},
  {title: "The Art of Jesse Osborne", heading: "Jesse Osborne of Dallas, Tx", body: "<div class=\"card bgclear\">\r\n<div class=\"card-body\">\r\n<div class=\"card-text\">\r\nLocated in the heart of East Dallas, <a class=\"btn btn-sm btn-outline-success\" href=\"https://www.facebook.com/mr.jesseosborne\">Jesse Osborne</a> creates amazing art on canvas as well as wire and stones. Come by the Deep Ellum Arts Company and see what the people have to offer\r\n</div>\r\n</div>\r\n</div>\r\n<div class=\"card bgclear\">\r\n<div class=\"card-body\">\r\n<div class=\"card-text\">\r\n<a class=\"btn btn-sm btn-outline-info\" href=\"https://www.facebook.com/mr.jesseosborne\"><image src=\"http://localhost:3000/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBEUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--96cc080c70d44cee29d15fedf73d85d566043e74/FB_IMG_1542134218814.jpg\"></a>\r\n</div>\r\n</div>\r\n</div>\r\n<div class=\"card bgclear\">\r\n<div class=\"card-body\">\r\n<div class=\"card-text\">\r\n<a class=\"btn btn-sm btn-outline-info\" href=\"https://www.facebook.com/mr.jesseosborne\"><image src=\"http://localhost:3000/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBEZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c7fab08542eb3526e09c9846eb508a7a03e14fc3/FB_IMG_1542134282547.jpg\"></a>\r\n</div>\r\n</div>\r\n</div>\r\n<div class=\"card bgclear\">\r\n<div class=\"card-body\">\r\n<div class=\"card-text\">\r\n<a class=\"btn btn-sm btn-outline-info\" href=\"https://www.facebook.com/mr.jesseosborne\"><image src=\"http://localhost:3000/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBEdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--40b9f6a8bc104f6dfc9d68377e98e1cfa8bd833b/FB_IMG_1542134252792.jpg\"></a>\r\n<a class=\"btn btn-sm btn-outline-info\" href=\"https://www.facebook.com/mr.jesseosborne\"><image src=\"http://localhost:3000/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBFQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--260682d8943aed02820a31e3e2c75c7924c478dc/FB_IMG_1542134305230.jpg\"></a>\r\n</div></div></div>", style_id: 1, user_id: 1, photo_id: 7}
])
